org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-functionalstorage
addon_name=BlueMap Functional Storage Add-on
addon_version=0.1.0-alpha.2
addon_group=io.github.jan-guenter
artifact_id=bluemap-functional-storage-addon
bluemap_version=5.22-feature.backport-5.23-stateless-java-web-server-46
accepted_jar_size=85323
accepted_jar_sha256=0bc4c0ed0195093487967260fc8ec2dbb4c9f389635098deb1bcc9e7839c1cfc
accepted_sources_jar_size=42745
accepted_sources_jar_sha256=9d1fedeedeb1c90ee7ba978e12a59d0429693fcae512458cf3fad75e05e449d6
accepted_pom_size=1397
accepted_pom_sha256=10363158b57fbf999d7bfa833cb579bf72d621864464a6407130850c4d04e2bc
accepted_module_size=2894
accepted_module_sha256=4b07b9d47bc58e1099f06544a96e0f729d56e2df92934f510f20c60f8f979581
