org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-functionalstorage
addon_name=BlueMap Functional Storage Add-on
addon_version=0.1.0-alpha.2
addon_group=io.github.jan-guenter
artifact_id=bluemap-functional-storage-addon
bluemap_version=5.22-feature.backport-5.23-stateless-java-web-server-46
accepted_jar_size=89631
accepted_jar_sha256=a8f0fd42f34d5902993ecd4b69c3bd464c077de3100cd1c6380add81d43e181b
accepted_sources_jar_size=45156
accepted_sources_jar_sha256=16dd06573a792d42026576a36b572bdb28064767f18a2deadba74dedd0bf03af
accepted_pom_size=1397
accepted_pom_sha256=10363158b57fbf999d7bfa833cb579bf72d621864464a6407130850c4d04e2bc
accepted_module_size=2894
accepted_module_sha256=5cd7042232eea989598c2d07d30c98bdca321d7f964aa68c9b5a6eee6e26b845
