org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-functionalstorage
addon_name=BlueMap Functional Storage Add-on
addon_version=0.1.0-alpha.1
addon_group=io.github.jan-guenter
artifact_id=bluemap-functional-storage-addon
bluemap_version=5.22-agent.backport-5.22-mc1.21.1-2
accepted_jar_size=82274
accepted_jar_sha256=ffe80812802c2c8f68d50ee74f17dd492561f3b44a9e650545064f66e285b048
accepted_sources_jar_size=39515
accepted_sources_jar_sha256=5b5b91d6d17f658a8de6dc99920e39bbe0e54518d5f2b9093760c9e17b13d9ef
accepted_pom_size=1397
accepted_pom_sha256=1d037275fa62154cf962e408497235e43d96e039a2eb39b6e142638320a04d0a
accepted_module_size=2894
accepted_module_sha256=2ba7a4cc10ebcc230cf2128bbf086817985d94e7efa0a6e2945866e043ea330f
