# Generated by gallery/generate.py; do not edit.
scoreboard objectives add fs_gallery dummy
scoreboard players add #builds fs_gallery 0
execute if score #builds fs_gallery matches 1.. run tellraw @a [{"text":"Functional Storage gallery already built; guard retained it."}]
execute if score #builds fs_gallery matches 0 run function functionalstorage_gallery:build_once
