# Generated by gallery/generate.py; do not edit.
scoreboard players add #builds fs_gallery 1
forceload add 160 160 191 191
function functionalstorage_gallery:clear
fill 160 99 160 191 99 191 minecraft:smooth_stone
# A1: framed 1 north
setblock 164 100 164 functionalstorage:framed_1[facing=north,subfacing=down,locked=false]
data merge block 164 100 164 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}}
# A2: framed 2 east locked
setblock 170 100 164 functionalstorage:framed_2[facing=east,subfacing=down,locked=true]
data merge block 170 100 164 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}}
# A3: framed 4 south inverted
setblock 176 100 164 functionalstorage:framed_4[facing=south,subfacing=up,locked=false]
data merge block 176 100 164 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}}
# A4: compacting west inverted locked
setblock 182 100 164 functionalstorage:compacting_framed_drawer[facing=west,subfacing=up,locked=true]
data merge block 182 100 164 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}}
# B1: simple compacting floor north
setblock 164 100 170 functionalstorage:framed_simple_compacting_drawer[facing=down,subfacing=north,locked=false]
data merge block 164 100 170 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}}
# B2: fluid 1 ceiling locked empty
setblock 170 100 170 functionalstorage:framed_fluid_1[facing=up,subfacing=down,locked=true]
data merge block 170 100 170 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}}
# B3: fluid 2 floor east empty
setblock 176 100 170 functionalstorage:framed_fluid_2[facing=down,subfacing=east,locked=false]
data merge block 176 100 170 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}}
# B4: fluid 4 floor south locked empty
setblock 182 100 170 functionalstorage:framed_fluid_4[facing=down,subfacing=south,locked=true]
data merge block 182 100 170 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}}
# C1: storage controller west
setblock 164 100 176 functionalstorage:framed_storage_controller[subfacing=west]
data merge block 164 100 176 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}}
# C2: controller extension east
setblock 170 100 176 functionalstorage:framed_controller_extension[subfacing=east]
data merge block 170 100 176 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}}
# C3: unstyled framed 1 native shell
setblock 176 100 176 functionalstorage:framed_1[facing=down,subfacing=west,locked=false]
data merge block 176 100 176 {framedDrawerModelData:{}}
# C4: ordinary oak 1 stock control
setblock 182 100 176 functionalstorage:oak_1[facing=north,subfacing=down,locked=false]
function functionalstorage_gallery:verify_immediate
schedule function functionalstorage_gallery:verify_20t 20t replace
schedule function functionalstorage_gallery:verify_100t 100t replace
