# Generated by gallery/generate.py; do not edit.
function functionalstorage_gallery:verify
scoreboard players operation #immediate_failures fs_gallery = #failures fs_gallery
scoreboard players operation #immediate_checked fs_gallery = #checked fs_gallery
tellraw @a [{"text":"Functional Storage gallery immediate: "},{"score":{"name":"#immediate_checked","objective":"fs_gallery"}},{"text":" checks, "},{"score":{"name":"#immediate_failures","objective":"fs_gallery"}},{"text":" failures"}]
