# Generated by gallery/generate.py; do not edit.
function functionalstorage_gallery:verify
scoreboard players operation #100t_failures fs_gallery = #failures fs_gallery
scoreboard players operation #100t_checked fs_gallery = #checked fs_gallery
tellraw @a [{"text":"Functional Storage gallery 100t: "},{"score":{"name":"#100t_checked","objective":"fs_gallery"}},{"text":" checks, "},{"score":{"name":"#100t_failures","objective":"fs_gallery"}},{"text":" failures"}]
