# Generated by gallery/generate.py; do not edit.
function functionalstorage_gallery:verify
scoreboard players operation #20t_failures fs_gallery = #failures fs_gallery
scoreboard players operation #20t_checked fs_gallery = #checked fs_gallery
