# Generated by gallery/generate.py; do not edit.
scoreboard players set #failures fs_gallery 0
scoreboard players set #checked fs_gallery 0
# A1: framed 1 north
execute unless block 164 100 164 functionalstorage:framed_1[facing=north,subfacing=down,locked=false] run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
execute unless data block 164 100 164 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}} run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
# A2: framed 2 east locked
execute unless block 170 100 164 functionalstorage:framed_2[facing=east,subfacing=down,locked=true] run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
execute unless data block 170 100 164 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}} run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
# A3: framed 4 south inverted
execute unless block 176 100 164 functionalstorage:framed_4[facing=south,subfacing=up,locked=false] run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
execute unless data block 176 100 164 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}} run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
# A4: compacting west inverted locked
execute unless block 182 100 164 functionalstorage:compacting_framed_drawer[facing=west,subfacing=up,locked=true] run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
execute unless data block 182 100 164 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}} run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
# B1: simple compacting floor north
execute unless block 164 100 170 functionalstorage:framed_simple_compacting_drawer[facing=down,subfacing=north,locked=false] run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
execute unless data block 164 100 170 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}} run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
# B2: fluid 1 ceiling locked empty
execute unless block 170 100 170 functionalstorage:framed_fluid_1[facing=up,subfacing=down,locked=true] run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
execute unless data block 170 100 170 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}} run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
# B3: fluid 2 floor east empty
execute unless block 176 100 170 functionalstorage:framed_fluid_2[facing=down,subfacing=east,locked=false] run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
execute unless data block 176 100 170 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}} run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
# B4: fluid 4 floor south locked empty
execute unless block 182 100 170 functionalstorage:framed_fluid_4[facing=down,subfacing=south,locked=true] run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
execute unless data block 182 100 170 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}} run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
# C1: storage controller west
execute unless block 164 100 176 functionalstorage:framed_storage_controller[subfacing=west] run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
execute unless data block 164 100 176 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}} run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
# C2: controller extension east
execute unless block 170 100 176 functionalstorage:framed_controller_extension[subfacing=east] run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
execute unless data block 170 100 176 {framedDrawerModelData:{particle:"minecraft:oak_planks",side:"minecraft:oak_planks",front:"minecraft:bricks",front_divider:"minecraft:gold_block"}} run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
# C3: unstyled framed 1 native shell
execute unless block 176 100 176 functionalstorage:framed_1[facing=down,subfacing=west,locked=false] run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
execute unless data block 176 100 176 framedDrawerModelData run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
execute if data block 176 100 176 framedDrawerModelData.particle run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
execute if data block 176 100 176 framedDrawerModelData.side run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
execute if data block 176 100 176 framedDrawerModelData.front run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
execute if data block 176 100 176 framedDrawerModelData.front_divider run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
# C4: ordinary oak 1 stock control
execute unless block 182 100 176 functionalstorage:oak_1[facing=north,subfacing=down,locked=false] run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
execute if data block 182 100 176 framedDrawerModelData run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
execute unless score #builds fs_gallery matches 1 run scoreboard players add #failures fs_gallery 1
scoreboard players add #checked fs_gallery 1
